import asyncio
import subprocess
import os
import re
from pathlib import Path
from typing import Optional, List, Dict, Any, Callable, TypedDict, Literal
from collections import deque
from datetime import datetime
from app.core.game_detector import detect_game_installations
from app.utils.path_utils import make_executable
from app.config import settings
from app.core.launch_logger import (
    get_launch_logger, LogLevel, LogSource, LaunchPhase
)
from app.core.process_monitor import ProcessMonitor, ProcessStatus


class LaunchResultDict(TypedDict):
    status: Literal["success", "error"]
    message: str
    pid: Optional[int]


OutputCallback = Callable[[str], None]

class LaunchError(Exception):
    """Exception raised during game launch"""
    pass

class Launcher:
    """Handles game launching and redscript compilation monitoring"""
    
    def __init__(self, game_path: Optional[Path] = None) -> None:
        self.game_path: Optional[Path] = game_path
        self._current_process: Optional[asyncio.subprocess.Process] = None
        self._is_launching: bool = False
        self._process_monitor: Optional[ProcessMonitor] = None
        self._launch_logger = get_launch_logger()
        self._log_buffer: deque[Dict[str, Any]] = deque(maxlen=1000)
        self._current_session_id: Optional[str] = None

    async def get_game_path(self) -> Path:
        """Get game path if not set, or verify it exists"""
        if self.game_path:
            if self.game_path.exists():
                return self.game_path
            raise LaunchError(f"Specified game path does not exist: {self.game_path}")
        
        installations = await detect_game_installations()
        if not installations:
            raise LaunchError(f"{settings.game_name} installation not detected")
        
        self.game_path = Path(installations[0]["path"])
        return self.game_path

    async def prepare_launch(self) -> Path:
        """Ensure launch script exists and is executable"""
        game_path = await self.get_game_path()
        
        # Check for launch_red4ext.sh first (preferred)
        launch_script = game_path / "launch_red4ext.sh"
        if not launch_script.exists():
            # Fallback to launch_modded.sh
            launch_script = game_path / "launch_modded.sh"
        
        if not launch_script.exists():
            # Create a default launch script if missing
            # This is a basic version for macOS (GPTK/CrossOver/Whisky)
            # Typically looks like: ./Cyberpunk2077.app/Contents/MacOS/Cyberpunk2077
            self._create_default_launch_script(launch_script)
            
        make_executable(launch_script)
        return launch_script

    def _create_default_launch_script(self, script_path: Path) -> None:
        """Creates a basic launch script for macOS"""
        app_bundle = f"{settings.game_name}.app"
        # Try to find the actual .app name in the directory
        for item in self.game_path.iterdir():
            if item.suffix == ".app":
                app_bundle = item.name
                break

        content = f"""#!/bin/bash
# {settings.game_name} Modded Launch Script for macOS
# Generated by macOS Mod Manager

cd "$(dirname "$0")"
./{app_bundle}/Contents/MacOS/{settings.game_domain}
"""
        script_path.write_text(content)

    async def launch_game(self, on_output: Optional[OutputCallback] = None) -> LaunchResultDict:
        """Launch the game and monitor output for redscript errors"""
        if self._is_launching:
            return {"status": "error", "message": "Launch already in progress"}
        
        self._is_launching = True
        
        # Start new launch session
        self._current_session_id = self._launch_logger.start_session()
        self._launch_logger.log(
            "Starting game launch...",
            level=LogLevel.INFO,
            source=LogSource.LAUNCHER,
            phase=LaunchPhase.PRE_LAUNCH
        )
        
        launch_script = await self.prepare_launch()
        
        self._launch_logger.log(
            f"Using launch script: {launch_script.name}",
            level=LogLevel.INFO,
            source=LogSource.LAUNCHER,
            phase=LaunchPhase.LAUNCHING
        )
        
        try:
            # Run the launch script and capture output
            process = await asyncio.create_subprocess_exec(
                str(launch_script),
                stdout=asyncio.subprocess.PIPE,
                stderr=asyncio.subprocess.STDOUT,  # Merge stderr into stdout
                cwd=str(self.game_path)
            )
            self._current_process = process
            
            # Create process monitor
            self._process_monitor = ProcessMonitor(process.pid)
            
            self._launch_logger.log(
                f"Game process started (PID: {process.pid})",
                level=LogLevel.INFO,
                source=LogSource.LAUNCHER,
                phase=LaunchPhase.LAUNCHING
            )
            self._launch_logger.update_session_status("running", self._current_session_id)
            
            # Start background monitoring
            asyncio.create_task(self._monitor_output(process, on_output))
            
            return LaunchResultDict(
                status="success",
                message="Game launched",
                pid=process.pid
            )
        except Exception as e:
            self._is_launching = False
            self._launch_logger.log(
                f"Failed to launch game: {str(e)}",
                level=LogLevel.ERROR,
                source=LogSource.LAUNCHER,
                phase=LaunchPhase.STOPPED
            )
            self._launch_logger.update_session_status("failed", self._current_session_id)
            raise LaunchError(f"Failed to launch game: {str(e)}")

    async def _monitor_output(self, process: asyncio.subprocess.Process, on_output: Optional[OutputCallback]) -> None:
        """Monitor stdout and stderr for compilation errors"""
        try:
            self._launch_logger.update_session_status("running", self._current_session_id)
            self._launch_logger.log(
                "Game process started, monitoring output...",
                level=LogLevel.INFO,
                source=LogSource.LAUNCHER,
                phase=LaunchPhase.RUNNING
            )
            
            while True:
                line = await process.stdout.readline()
                if not line:
                    break
                
                decoded_line = line.decode(errors='ignore').strip()
                if not decoded_line:
                    continue
                
                # Determine log level and source
                level = LogLevel.INFO
                source = LogSource.LAUNCHER
                
                decoded_lower = decoded_line.lower()
                if '[error]' in decoded_lower or 'error:' in decoded_lower:
                    level = LogLevel.ERROR
                elif '[warn]' in decoded_lower or 'warning:' in decoded_lower:
                    level = LogLevel.WARNING
                elif '[debug]' in decoded_lower:
                    level = LogLevel.DEBUG
                
                # Detect source
                if 'red4ext' in decoded_lower:
                    source = LogSource.RED4EXT
                elif 'tweakxl' in decoded_lower:
                    source = LogSource.TWEAKXL
                elif 'archivexl' in decoded_lower:
                    source = LogSource.ARCHIVEXL
                elif 'redscript' in decoded_lower or '.reds' in decoded_lower:
                    source = LogSource.REDSCRIPT
                elif 'cyberpunk' in decoded_lower or 'game' in decoded_lower:
                    source = LogSource.GAME
                
                # Log to buffer and logger
                log_entry = {
                    "timestamp": datetime.now(),
                    "level": level.value,
                    "message": decoded_line,
                    "source": source.value
                }
                self._log_buffer.append(log_entry)
                
                self._launch_logger.log(
                    decoded_line,
                    level=level,
                    source=source,
                    phase=LaunchPhase.RUNNING,
                    session_id=self._current_session_id
                )
                
                if on_output:
                    on_output(decoded_line)
                
                # Check for redscript errors
                if "[Error]" in decoded_line and (".reds" in decoded_line or "redscript" in decoded_line.lower()):
                    self._launch_logger.log(
                        f"REDscript error detected: {decoded_line}",
                        level=LogLevel.ERROR,
                        source=LogSource.REDSCRIPT,
                        phase=LaunchPhase.RUNNING,
                        session_id=self._current_session_id
                    )
        except Exception as e:
            self._launch_logger.log(
                f"Error monitoring process: {str(e)}",
                level=LogLevel.ERROR,
                source=LogSource.LAUNCHER,
                phase=LaunchPhase.STOPPED,
                session_id=self._current_session_id
            )
        finally:
            self._is_launching = False
            self._launch_logger.update_session_status("stopped", self._current_session_id)
            self._launch_logger.log(
                "Game process stopped",
                level=LogLevel.INFO,
                source=LogSource.LAUNCHER,
                phase=LaunchPhase.STOPPED,
                session_id=self._current_session_id
            )
            self._current_process = None
            self._process_monitor = None

    def stop_game(self) -> bool:
        """Stop the currently running game process (graceful termination)"""
        if self._process_monitor:
            success = self._process_monitor.terminate()
            if success:
                self._launch_logger.log(
                    "Game stop signal sent (SIGTERM)",
                    level=LogLevel.INFO,
                    source=LogSource.LAUNCHER,
                    phase=LaunchPhase.STOPPED,
                    session_id=self._current_session_id
                )
            return success
        elif self._current_process:
            try:
                self._current_process.terminate()
                self._launch_logger.log(
                    "Game stop signal sent (SIGTERM)",
                    level=LogLevel.INFO,
                    source=LogSource.LAUNCHER,
                    phase=LaunchPhase.STOPPED,
                    session_id=self._current_session_id
                )
                return True
            except OSError:
                return False
        return False
    
    def force_kill_game(self) -> bool:
        """Force kill the currently running game process"""
        if self._process_monitor:
            success = self._process_monitor.kill()
            if success:
                self._launch_logger.log(
                    "Game force killed (SIGKILL)",
                    level=LogLevel.WARNING,
                    source=LogSource.LAUNCHER,
                    phase=LaunchPhase.STOPPED,
                    session_id=self._current_session_id
                )
            return success
        elif self._current_process:
            try:
                self._current_process.kill()
                self._launch_logger.log(
                    "Game force killed (SIGKILL)",
                    level=LogLevel.WARNING,
                    source=LogSource.LAUNCHER,
                    phase=LaunchPhase.STOPPED,
                    session_id=self._current_session_id
                )
                return True
            except OSError:
                return False
        return False
    
    def get_launch_logs(self, limit: Optional[int] = None) -> List[Dict[str, Any]]:
        """Get buffered launch logs"""
        if self._current_session_id:
            return self._launch_logger.get_logs(
                session_id=self._current_session_id,
                limit=limit
            )
        return []
    
    def get_process_metrics(self) -> Optional[Dict[str, Any]]:
        """Get current process metrics"""
        if self._process_monitor:
            return self._process_monitor.get_metrics()
        elif self._current_process:
            try:
                monitor = ProcessMonitor(self._current_process.pid)
                self._process_monitor = monitor
                return monitor.get_metrics()
            except Exception:
                return None
        return None
    
    def set_process_priority(self, nice: int) -> bool:
        """Set process priority (nice level)"""
        if self._process_monitor:
            return self._process_monitor.set_priority(nice)
        elif self._current_process:
            try:
                monitor = ProcessMonitor(self._current_process.pid)
                self._process_monitor = monitor
                return monitor.set_priority(nice)
            except Exception:
                return False
        return False
    
    def get_current_session_id(self) -> Optional[str]:
        """Get current launch session ID"""
        return self._current_session_id
